CREATE TABLE COURSE_SESSION
 (
   ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
   LOCATION_ID INT NOT NULL  ,
   COURSE_CODE VARCHAR(6) NOT NULL  ,
   START_DATE DATE NOT NULL  ,
   END_DATE DATE NOT NULL  ,
   MAXCS INTEGER NOT NULL  
   , PRIMARY KEY (ID) 
 );


CREATE  INDEX I_FK_COURSE_SESSION_LOCATION
     ON COURSE_SESSION (LOCATION_ID ASC);

CREATE  INDEX I_FK_COURSE_SESSION_COURSE
     ON COURSE_SESSION (COURSE_CODE ASC);


CREATE TABLE CLIENT
 (
   ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
   LASTNAME VARCHAR(50) NOT NULL  ,
   FIRSTNAME VARCHAR(50) NOT NULL  ,
   ADDRESS VARCHAR(75) NOT NULL  ,
   PHONE VARCHAR(10) NOT NULL  ,
   EMAIL VARCHAR(50),
   COURSE_SESSION_ID INT NOT NULL
   , PRIMARY KEY (ID) 
 );

CREATE  INDEX I_FK_CLIENT_COURSE_SESSION
     ON CLIENT (COURSE_SESSION_ID ASC);

CREATE TABLE COURSE
 (
   CODE VARCHAR(6) NOT NULL  ,
   TITLE VARCHAR(30) NOT NULL  
   , PRIMARY KEY (CODE) 
 );


CREATE TABLE LOCATION
 (
   ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
   CITY VARCHAR(50) NOT NULL  
   , PRIMARY KEY (ID) 
 );


ALTER TABLE COURSE_SESSION 
  ADD CONSTRAINT FK_COURSE_SESSION_LOCATION FOREIGN KEY (LOCATION_ID)
      REFERENCES LOCATION (ID) ;


ALTER TABLE COURSE_SESSION 
  ADD CONSTRAINT FK_COURSE_SESSION_COURSE FOREIGN KEY (COURSE_CODE)
      REFERENCES COURSE (CODE) ;


ALTER TABLE CLIENT 
  ADD CONSTRAINT FK_CLIENT_COURSE_SESSION FOREIGN KEY (COURSE_SESSION_ID)
      REFERENCES COURSE_SESSION (ID) ;
